ECE_LAB_COURSES = {
    "BASIC ELECTRICAL AND ELECTRONICS ENGINEERING",
    "BASIC ELECTRICAL AND ELECTRONICS ENGINEERING LABORATORY",
    "PRINCIPLES OF ELECTRONICS",
    "PRINCIPLES OF ELECTRONICS LABORATORY",
    "ELECTRONICS FOR ROBOTS",
    "DIGITAL ELECTRONICS",
}

COMPUTER_LAB_ROOM_TYPES = {
    "Computer Lab",
}

ECE_ROOM_TYPES = {
    "ECE Lab",
}

MAX_FACULTY_LOAD = 23

MAX_LAB_STUDENTS = 36

WORKING_DAYS = 5